apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://mojo2600.github.io/pihole-kubernetes/'
    targetRevision: 2.30.0
    chart: pihole
    helm:
      values: |
        serviceTCP:
          type: LoadBalancer
        serviceUDP:
          type: LoadBalancer
        DNS1: "1.1.1.1"
        DNS2: "8.8.8.8"
        adminPassword: "password"
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
