apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:lGyL6Ib2afRVNzjzag6WvAccCf44MEmaLJlFl2ytda1RjL8NGGO/9w==,iv:9KW8HWpmR7J5in/zenmTGsflJ1x/pSqOZgb6by+eYeI=,tag:+q06e/+JbjpuQOKcANAHDw==,type:str]
sops:
    age:
        - recipient: age1q54mz35khqtr5ha307p6axag895ctjgq3gv3xd0dp30ncy073fpscax4yk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Z2J0ak9ySjZzY2kzY0tD
            eFU5MHZURnRKdzdKbDEyS2ltdnBrZU9HK1VVClhxNGsrMjlNUkY0TngvaWlxMFI5
            enNSNUVVWjl3M01LMzViMVhoS3MySVUKLS0tIDVLc0Y5QmlyazhzeG0zR09NMUFF
            Q3BPTHFDbENiMmIrV2NESU9adEhId0EKuez2LAgUuHZRIhtUX2fbvypb0FQ7S09B
            9xQYfttFgGZaF3y2Rfhk1t1vvNASzpF4vzZf2IJ2gGX3if/PZnJ+Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-28T22:40:39Z"
    mac: ENC[AES256_GCM,data:yTdnHHuPKnIWe+pDGPyfMZcqQRbOIJpoRVgMl5yfeI6hou9leZlce82+mRjyS5bRWdjG2RqsLRGE4F1eg0nUDRoHfGkwVA7fHx4fIIhxhd84jH6tHMY/GQ9D+tQVLTkRjGRfvfjuIvJSC9n4ZGKBx8i9NX1DspJ/uSiowgkXbBQ=,iv:CP4Djkk0pmV3EQmg7pIrOMzNtoZFNGMXF1CnI7W3M58=,tag:tO0uvGI+75LtrtTy3TjyWw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
