apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: butlercasa-wildcard-tls
  namespace: cert-manager
spec:
  secretName: butlercasa-wildcard-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "*.butlercasa.com"
  - "butlercasa.com"
