apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/zacharybutler/homelab.git'
    path: apps/networking/pihole
    helm:
      chart: pihole
      repo: https://mojo2600.github.io/pihole-kubernetes/
      targetRevision: 2.31.0
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

